### ISSUE TITLE
[Bug] 切后台会导致弹幕卡住不动

### ISSUE THREAD

**Issue by bbyuyund** [bggRGjQaUbCoE/PiliPalaX#46]
### 问题描述
请提供一个清晰而简明的问题描述。
release9版本之后，切后台再打开会导致弹幕静止不动。

### 复现步骤
请提供复现该问题所需的具体步骤。
打开弹幕，切后台，重启，稳定复现。

### 预期行为
请描述你期望的正确行为或结果。
正常继续显示。

### 错误日志
请提供设置->关于->错误日志中的内容，粘贴在下方代码框中。如果没有，请提供您的app版本号、系统版本、设备型号等相关信息。

```PiliPalaX错误日志
********************
------- 设备信息 -------
id: UP1A.231005.007
board: parrot
bootloader: unknown
brand: vivo
device: PD2353
display: PD2353_A_14.0.9.0.W10.V000L1
fingerprint: vivo/PD2353M/PD2353:14/UP1A.231005.007/compiler11191528:user/release-keys
hardware: qcom
host: comdg01150033
isPhysicalDevice: true
manufacturer: vivo
model: V2353DA
product: PD2353M
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: compiler11191528
versionPreviewSdk: 0
versionRelease: 14
versionSdk: 34
versionSecurityPatch: 2024-11-01
------- 应用信息 -------
environment: release
version: 1.0.22
appName: PiliPalaX
buildNumber: 123
packageName: com.example.pilipalax
---------- 错误信息 ----------
Null check operator used on a null value
------- 错误堆栈 -------
#0      ItemScrollController.jumpTo (package:scrollable_positioned_list/src/scrollable_positioned_list.dart:220)
#1      VideoReplyReplyController.customHandleResponse.<anonymous closure> (package:PiliPalaX/pages/video/detail/reply_reply/controller.dart:98)
#2      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397)
#3      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1331)
#4      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176)
#5      _invoke (dart:ui/hooks.dart:312)
#6      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419)
#7      _drawFrame (dart:ui/hooks.dart:283)
------- CUSTOM INFO -------

```

### 相关信息
请补充截图、录屏、BV号等其他有助于解决问题的信息。
错误日志来自手机，安卓系统vivo y200t，同样更新至release10（使用tab型布局）的安卓系统 小米平板也有同样问题，可稳定复现🥺（感谢大佬的开发，非常好用）

**Comment by bbyuyund** [comment]
补充:开启了后台播放功能，新的海量弹幕功能没有打开。描述中用词有误，不是切后台，重启软件，而是正常切屏到后台再切回。
