### ISSUE TITLE
[Bug] 應用在使用匯入功能會導致白屏產生

### ISSUE THREAD

**Issue by NeKoOuO** [bggRGjQaUbCoE/PiliPalaX#7]
### 问题描述
播放和進入SB選項會出現白屏

### 复现步骤
使用匯入功能後

### 预期行为
不應該有白屏

### 错误日志

```
PiliPalaX错误日志
********************
------- 设备信息 -------
model: iPhone
isPhysicalDevice: true
name: iPhone
identifierForVendor: DD0A1056-69F7-4C4D-86CF-EE2C1F05F699
localizedModel: iPhone
systemName: iOS
utsnameVersion: Darwin Kernel Version 24.2.0: Thu Nov 14 22:17:21 PST 2024; root:xnu-11215.62.3~2/RELEASE_ARM64_T8122
utsnameRelease: 24.2.0
utsnameMachine: iPhone16,2
utsnameNodename: localhost
utsnameSysname: Darwin
------- 应用信息 -------
environment: release
version: 1.0.22
appName: PiliPalaX
buildNumber: 123
packageName: com.example.pilipalax
---------- 错误信息 ----------
type 'List<dynamic>' is not a subtype of type 'List<int>'
------- 错误堆栈 -------
#0      GStorage.blockSettings (package:PiliPalaX/utils/storage.dart:27)
#1      _SponsorBlockPageState.initState (package:PiliPalaX/pages/setting/sponsor_block_page.dart:38)
#2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5748)
#3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#5      Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#6      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#15     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#22     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#28     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035)
#29     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7047)
#30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#33     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#36     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#37     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#39     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#40     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#44     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#45     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#46     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#47     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#51     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#55     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#56     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#57     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#58     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#59     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#62     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#66     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#67     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#68     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#69     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#70     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#74     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#75     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#76     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#77     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#78     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#82     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#83     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#84     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#85     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#86     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#87     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#88     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#90     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#91     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#92     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#93     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#94     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#97     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#98     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#99     Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#101    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#102    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#103    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#104    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#105    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#106    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#107    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#108    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#110    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#111    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#112    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#113    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#114    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#115    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#116    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#118    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#119    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#120    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#121    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#124    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#125    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#126    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#127    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#128    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#130    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#131    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#132    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#133    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#134    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#135    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#136    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#138    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#139    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#140    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#141    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#142    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#143    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#144    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#145    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#146    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#147    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#148    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#149    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#150    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#151    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#152    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#153    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#154    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#155    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#156    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#157    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#158    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#159    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#160    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#161    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#162    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#163    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#164    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#165    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#166    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#167    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#168    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#169    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#170    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#171    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#172    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#173    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#174    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#175    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#176    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#177    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#178    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#179    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#180    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#181    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#182    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#183    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#184    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#185    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#186    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#187    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#188    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#189    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#190    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#191    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#192    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#193    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#194    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#195    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#196    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#197    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#198    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#199    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#200    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#201    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#202    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#203    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#204    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#205    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#206    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#207    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#208    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#209    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#210    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#211    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#212    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#213    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#214    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5599)
#215    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5771)
#216    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#217    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#218    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035)
#219    Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#220    Element.updateChildren (package:flutter/src/widgets/framework.dart:4150)
#221    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7060)
#222    Element.updateChild (package:flutter/src/widgets/framework.dart:3941)
#223    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#224    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#225    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#226    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803)
#227    Element.updateChild (package:flutter/src/widgets/framework.dart:3941)
#228    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#229    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#230    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946)
#231    Element.updateChild (package:flutter/src/widgets/framework.dart:3941)
#232    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#233    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#234    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946)
#235    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105)
#236    Element.updateChild (package:flutter/src/widgets/framework.dart:3941)
#237    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#238    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#239    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#240    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803)
#241    Element.updateChild (package:flutter/src/widgets/framework.dart:3941)
#242    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#243    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#244    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946)
#245    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105)
#246    Element.updateChild (package:flutter/src/widgets/framework.dart:3941)
#247    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#248    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#249    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#250    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803)
#251    Element.updateChild (package:flutter/src/widgets/framework.dart:3941)
#252    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#253    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#254    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#255    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803)
#256    Element.updateChild (package:flutter/src/widgets/framework.dart:3941)
#257    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907)
#258    Element.updateChild (package:flutter/src/widgets/framework.dart:3941)
#259    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907)
#260    Element.updateChild (package:flutter/src/widgets/framework.dart:3941)
#261    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#262    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#263    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946)
#264    Element.updateChild (package:flutter/src/widgets/framework.dart:3941)
#265    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#266    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#267    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946)
#268    Element.updateChild (package:flutter/src/widgets/framework.dart:3941)
#269    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#270    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#271    Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#272    BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2693)
#273    BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2752)
#274    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3048)
#275    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1162)
#276    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468)
#277    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397)
#278    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318)
#279    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176)
#280    _invoke (dart:ui/hooks.dart:312)
#281    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419)
#282    _drawFrame (dart:ui/hooks.dart:283)
------- CUSTOM INFO -------
```

### 相关信息

https://github.com/user-attachments/assets/021d9773-75cf-4580-ad69-22bb590d6308

https://github.com/user-attachments/assets/81de8096-8a72-4984-b209-50d304be8e35

**Comment by bggRGjQaUbCoE** [comment]
fixed
