### ISSUE TITLE
[Bug] gRPC問題導致留言區無法正常加載

### ISSUE THREAD

**Issue by NeKoOuO** [bggRGjQaUbCoE/PiliPalaX#8]
### 问题描述

**Comment by bggRGjQaUbCoE** [comment]
你用了自签名证书？
https://stackoverflow.com/questions/54285172/how-to-solve-flutter-certificate-verify-failed-error-while-performing-a-post-req

**Comment by NeKoOuO** [comment]
這個是Android 的報錯

**Comment by NeKoOuO** [comment]
這個是iPhone 的
![image](https://github.com/user-attachments/assets/dd58d670-6b63-498f-b6b4-69bc6c521fbe)

**Comment by NeKoOuO** [comment]
> 你用了自签名证书？
> https://stackoverflow.com/questions/54285172/how-to-solve-flutter-certificate-verify-failed-error-while-performing-a-post-req

應該跟那個沒關係

**Comment by NeKoOuO** [comment]
```
PiliPalaX错误日志
********************
------- 设备信息 -------
id: TKQ1.221114.001
board: cas
bootloader: unknown
brand: Xiaomi
device: cas
display: TKQ1.221114.001 release-keys
fingerprint: Xiaomi/cas/cas:13/RKQ1.211001.001/V14.0.2.0.TJJCNXM:user/release-keys
hardware: qcom
host: xiaomi.eu
isPhysicalDevice: true
manufacturer: Xiaomi
model: M2007J1SC
product: cas
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.2.0.TJJCNXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-04-01
------- 应用信息 -------
environment: release
version: 1.0.22
appName: PiliPalaX
buildNumber: 123
packageName: com.example.pilipalax
---------- 错误信息 ----------
"RcmdController" not found. You need to call "Get.put(RcmdController())" or "Get.lazyPut(()=>RcmdController())"
------- 错误堆栈 -------
#0      GetInstance.find (package:get/get_instance/src/get_instance.dart:306)
#1      Inst.find (package:get/get_instance/src/extension_instance.dart:69)
#2      Inst.find.<anonymous closure> (package:get/get_instance/src/extension_instance.dart:69)
#3      HomeController.animateToTop (package:PiliPalaX/pages/home/controller.dart:58)
#4      _MainAppState.setIndex (package:PiliPalaX/pages/main/view.dart:78)
#5      NavigationBar._handleTap.<anonymous closure> (package:flutter/src/material/navigation_bar.dart:223)
#6      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1170)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:351)
#8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:656)
#9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:313)
#10     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:283)
#11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:169)
#12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:505)
#13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:481)
#14     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:450)
#15     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:426)
#16     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:389)
#17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:336)
#18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:305)
#19     _invoke1 (dart:ui/hooks.dart:328)
#20     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442)
#21     _dispatchPointerDataPacket (dart:ui/hooks.dart:262)
------- CUSTOM INFO -------
```

**Comment by bggRGjQaUbCoE** [comment]
提供关闭gRPC加载评论，可下载测试
https://github.com/bggRGjQaUbCoE/PiliPalaX/actions/runs/12086098309

**Comment by NeKoOuO** [comment]
確實解決了 是不是可以 close issue 了 還是說要保留 gRPC 問題的狀況

**Comment by bggRGjQaUbCoE** [comment]
> 是ip和cdn的原因吗 香港ip也是显示报错code14

暂不清楚，复现不了

**Comment by vvb2060** [comment]
grpc.biliapi.net 这个域名进了广告域名列表，各种去广告dns和代理软件会解析到0.0.0.0或者打断连接

**Comment by NeKoOuO** [comment]
> grpc.biliapi.net 这个域名进了广告域名列表，各种去广告dns和代理软件会解析到0.0.0.0或者打断连接
> 
> 
> 
> https://github.com/AdguardTeam/AdguardFilters/commit/1358b4acbaf6731a68f6a0af5be08ec8590482c9

原來是這樣⋯感謝
